name: cascade
channels:
  - defaults
  - conda-forge
dependencies:
  # Core dependencies
  - python==3.11

  # Computational chemistry
  - packmol
  - cp2k

  # Pip packages for the Python modules
  - pip
  - pip:
      # General utilities
      - matplotlib
      - papermill
      - scikit-learn>=1
      - jupyterlab
      - pandas

      # ML side
      - -e .[mace,chgnet,ani]
