name: cascade
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  # Core dependencies
  - python==3.10
  - matplotlib
  - scikit-learn>=1
  - jupyterlab
  - pytorch==2.4.1
  - pandas
  - pytest
  - flake8
  - pip

  # Computational chemistry
#  - packmol

  # For nersc's jupyterlab
  - ipykernel

# Pip packages for all of them
  - pip:
      - git+https://gitlab.com/ase/ase.git
      - git+https://github.com/ACEsuit/mace.git
      - schnetpack
      - mlflow
      - pytorch-ignite
      - python-git-info
      - tqdm
      - papermill
      - -e .
